language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "rake yast2-core-dev yast2 yast2-devtools doxygen yast2-testsuite libstorage5-dev libstorage5-ruby ruby-dbus yast2-installation" -g "rspec:2.14.1 yast-rake gettext"
script:
    - rake check:syntax
    - rake check:pot
    - make -f Makefile.cvs
    - make -j 4
    - sudo make install
    - make check

